model:
  type: "LSTM"
  input_size: 9
  hidden_size: 64
  hidden_layers: 3
  output_size: 1
  
training:
  batch_size: 512
  learning_rate: 0.001
  window_size: 25
  stride_size: 20
  num_features: 9
  patience: 4
  min_delta: 0.00008

data:
  model_dir: "outputs/models/lstm"